services:
  # ==========================================================================================
  # Database
  # ==========================================================================================
  db:
    # https://github.com/docker-library/docs/blob/master/mariadb/README.md
    image: mariadb:10
    restart: always
    # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    healthcheck:
    # https://mariadb.com/kb/en/using-healthcheck-sh/
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
    # https://github.com/docker-library/docs/blob/master/mariadb/README.md#where-to-store-data
      - db_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mariadb/sql:/docker-entrypoint-initdb.d

  # ==========================================================================================
  # Redis
  # ==========================================================================================
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  # ==========================================================================================
  # Application
  # ==========================================================================================
  app:
    image: laravel_app
    build:
      context: ./
      dockerfile: ./docker/laravel/Dockerfile
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:5173
    environment:
      # set only the ones that are needed by the entrypoint script to prevent shadowing the env file
      - APP_ENV=${APP_ENV}
      - DB_CONNECTION=${DB_CONNECTION}
      - APP_KEY=${APP_KEY}
    volumes:
      - .env:/var/www/laravel/.env
    restart: always
    depends_on:
      - db

  # ==========================================================================================
  # Adminer
  # ==========================================================================================
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data:
  redis_data:
